spring:
  datasource:
    # 服务器上的数据库
    url: jdbc:mysql://47.98.135.123:5555/test?useUnicode=true&characterEncoding=utf8
    # 本地测试数据库
    # url: jdbc:mysql://127.0.0.1:55555/test?useUnicode=true&characterEncoding=utf8
    username: root
    password: wsqd19950428
    driver-class-name: com.mysql.jdbc.Driver

    # 初始化大小，最小，最大
    initialSize: 5
    minIdleSize: 10
    maxActive: 1000
    # 获取配置连接的等待超时时间

  #静态资源在如下位置为默认文件夹（5个）：
  #/META-INF/resources
  #/resources
  #/static/
  #/public/
  #/ 根目录

  # 如果不指定则这几个都生效
  resources:
    static-locations: classpath:/static/

#  security:
#    user:
#      name: user
#      password: 123456
#      roles: user, admin

server:
  port: 8010
  tomcat:
    uri-encoding: UTF-8

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml

